# Automatically label PRs based on changed files
# See https://github.com/actions/labeler/tree/v6/

documentation:
- changed-files:
  - any-glob-to-any-file:
    - 'docs/*'
    - '*.md'
    - 'triplets/*'
    - 'scripts/*'

'ci: GitHub Actions':
- changed-files:
  - any-glob-to-any-file: '.github/*'
